name: CI - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Node.js dependencies
        run: |
          cd server
          npm install

      - name: Install Python dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Node.js tests
        run: |
          cd server
          npm test || echo "Skipping tests (none yet)"

